version: '3.8'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    environment:
      LANG: en
      PASSWORD_HASH: ${PASSWORD_HASH}
      WG_HOST: ${VPN_HOST}
      WG_DEFAULT_DNS: ${DNS_SERVER}
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_ALLOWED_IPS: 0.0.0.0/0
      WG_PERSISTENT_KEEPALIVE: 25
      WG_MTU: 1420
      WG_POST_UP: iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT
      WG_POST_DOWN: iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -j MASQUERADE; iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT
    volumes:
      - /mnt/gluster/slowpool/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - public_network

networks:
  public_network:
    external: true
