apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  diskSelector: "hdd"
  dataLocality: "disabled"
  staleReplicaTimeout: "20"
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  diskSelector: "ssd"
  dataLocality: "disabled"
  staleReplicaTimeout: "20"
reclaimPolicy: Delete
volumeBindingMode: Immediate