version: '3.8'

services:
  adguard:
    image: adguard/adguardhome:v0.107.61
    networks:
      - public_network
    ports:
      - "53:53/tcp"    # DNS
      - "53:53/udp"    # DNS
    volumes:
      - /mnt/gluster/slowpool/adguard/work:/opt/adguardhome/work
      - /mnt/gluster/slowpool/adguard/conf:/opt/adguardhome/conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  public_network:
    external: true
