version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.55.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - /mnt/gluster/fastpool/prometheus/data:/prometheus
      - /mnt/gluster/slowpool/prometheus/config:/etc/prometheus
    ports:
      - "9090:9090"  # Comment out when not needed for debugging
    networks:
      - metrics_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G

networks:
  metrics_network:
    external: true