services:
  npmanager:
    image: 'jc21/nginx-proxy-manager:latest'
    networks:
      - public_network
    environment:
      DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
      # Disable built-in Let's Encrypt
      DISABLE_IPV6: 'true'
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

volumes:
  npm_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Main/nginxproxymanager/data"

  npm_letsencrypt:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Main/nginxproxymanager/letsencrypt"

networks:
  public_network:
    driver: overlay
    name: public_network
