---
apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: v1
kind: Secret
metadata:
  name: paperless-secrets
  namespace: paperless
type: Opaque
stringData:
  postgres-password: "${POSTGRES_PASS}"
  paperless-secret-key: "${PAPERLESS_SECRET_KEY}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  POSTGRES_DB: "paperless"
  POSTGRES_USER: "paperless"
  PAPERLESS_OCR_LANGUAGE: "spa"
  PAPERLESS_OCR_LANGUAGES: "eng"
  PAPERLESS_URL: "https://paper.test.local"
---