version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.2.0
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      HOMEPAGE_ALLOWED_HOSTS: home.vicugna.party
    volumes:
      - /mnt/gluster/fastpool/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public_network
#    ports:
#      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
        failure_action: rollback

networks:
  public_network:
    external: true