# Redis PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-redis-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-ssd
---
# PostgreSQL PVC (fast storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgres-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-ssd
---
# Paperless PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-paperless-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-hdd
---