# Redis PVC (fast storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 512Mi
---
# PostgreSQL PVC (fast storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
# Paperless unified storage PVC (slow storage)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-storage
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-hdd
  resources:
    requests:
      storage: 2Gi