# Paperless PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-paperless-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn-hdd
---
# Paperless Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      initContainers:
        - name: create-dirs
          image: busybox:1.35
          command: ['sh', '-c', 'mkdir -p /paperless-storage/data /paperless-storage/media /paperless-storage/export /paperless-storage/consume']
          volumeMounts:
            - name: paperless-storage
              mountPath: /paperless-storage
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          env:
            - name: PAPERLESS_REDIS
              value: "redis://redis:6379"
            - name: PAPERLESS_DBHOST
              value: "postgres"
            - name: PAPERLESS_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: paperless-config
                  key: POSTGRES_DB
            - name: PAPERLESS_DBUSER
              valueFrom:
                configMapKeyRef:
                  name: paperless-config
                  key: POSTGRES_USER
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: postgres-password
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-secrets
                  key: paperless-secret-key
            - name: PAPERLESS_OCR_LANGUAGE
              valueFrom:
                configMapKeyRef:
                  name: paperless-config
                  key: PAPERLESS_OCR_LANGUAGE
            - name: PAPERLESS_OCR_LANGUAGES
              valueFrom:
                configMapKeyRef:
                  name: paperless-config
                  key: PAPERLESS_OCR_LANGUAGES
            - name: PAPERLESS_URL
              valueFrom:
                configMapKeyRef:
                  name: paperless-config
                  key: PAPERLESS_URL
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: paperless-storage
              mountPath: /usr/src/paperless/data
              subPath: data
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: paperless-storage
          persistentVolumeClaim:
            claimName: paperless-paperless-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  selector:
    app: paperless
  ports:
    - port: 8000
      targetPort: 8000