apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nodea
  namespace: longhorn-system
spec:
  disks:
    hdd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/hdd-storage
      tags:
        - "hdd"
    ssd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/ssd-storage
      tags:
        - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nodeb
  namespace: longhorn-system
spec:
  disks:
    hdd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/hdd-storage
      tags:
        - "hdd"
    ssd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/ssd-storage
      tags:
        - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: nodec
  namespace: longhorn-system
spec:
  disks:
    hdd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/hdd-storage
      tags:
        - "hdd"
    ssd-disk:
      allowScheduling: true
      evictionRequested: false
      path: /mnt/ssd-storage
      tags:
        - "ssd"