apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3" # Change this to the amount of available nodes
  diskSelector: "slow"
  nodeSelector: ""
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3" # Change this to the amount of available nodes
  diskSelector: "fast"
  nodeSelector: ""