version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    networks:
      - public_network
      - redis_network
      - nextcloud_network
    environment:
      # Postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: nextcloud-db
      # Redis
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      # REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      # SMTP
      SMTP_HOST: ${SMTP_HOST}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTHTYPE: ${SMTP_AUTHTYPE}
      SMTP_NAME: ${SMTP_NAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      # Nextcloud
      # NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      # NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      # NEXTCLOUD_UPDATE: 1
      # NEXTCLOUD_INIT_SKIP_POSTGIS: 1
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      OVERWRITEPROTOCOL: https
    volumes:
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U your_user -d your_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nextcloud_network

volumes:
  nextcloud_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Main/nextcloud/config"

  nextcloud_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Main/nextcloud/data"

  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Databases/nextcloud"

networks:
  public_network:
    external: true

  redis_network:
    external: true

  nextcloud_network:
    driver: overlay
