
services:
  postgres:
    container_name: postgres
    image: postgres:latest
#    ports:
#      - "5432:5432"
    volumes:
      - .docker/druid/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=FoolishPassword
      - POSTGRES_USER=druid
      - POSTGRES_DB=druid

  # Need 3.5 or later for container nodes
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.10
#    ports:
#      - "2181:2181"
    environment:
      - ZOO_MY_ID=1

  coordinator:
    image: apache/druid:33.0.0
    container_name: coordinator
    volumes:
      - .docker/druid/shared:/opt/shared
      - .docker/druid/coordinator:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
#    ports:
#      - "8081:8081"
    command:
      - coordinator
    env_file:
      - environment

  broker:
    image: apache/druid:33.0.0
    container_name: broker
    volumes:
      - .docker/druid/broker:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
#    ports:
#      - "8082:8082"
    command:
      - broker
    env_file:
      - environment

  historical:
    image: apache/druid:33.0.0
    container_name: historical
    volumes:
      - .docker/druid/shared:/opt/shared
      - .docker/druid/historical:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
#    ports:
#      - "8083:8083"
    command:
      - historical
    env_file:
      - environment

  middlemanager:
    image: apache/druid:33.0.0
    container_name: middlemanager
    volumes:
      - .docker/druid/shared:/opt/shared
      - .docker/druid/middlemanager:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
#    ports:
#      - "8091:8091"
#      - "8100-8105:8100-8105"
    command:
      - middleManager
    env_file:
      - environment

  router:
    image: apache/druid:33.0.0
    container_name: router
    volumes:
      - .docker/druid/router:/opt/druid/var
    depends_on:
      - zookeeper
      - postgres
      - coordinator
    ports:
      - "8888:8888"
    command:
      - router
    env_file:
      - environment