version: '3.8'

services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:5.1.0-1
    ports:
      - "6881:6881/tcp"
      - "6881:6881/udp"
    environment:
      - WEBUI_HOST=0.0.0.0
      - WEBUI_PORT=8080
    volumes:
      - /mnt/gluster/slowpool/qbittorrent/config:/config
      - /mnt/gluster/slowpool/qbittorrent/downloads:/downloads
      - /mnt/gluster/slowpool/qbittorrent/torrent:/torrent
    tmpfs:
      - /tmp
    networks:
      - public_network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  public_network:
    external: true
