services:
  grafana:
    image: grafana/grafana:11.4.0
    environment:
      # Security
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
      # Server
      GF_SERVER_ROOT_URL: https://grafana.vicugna.party
      GF_SERVER_SERVE_FROM_SUB_PATH: 'false'
      # Database (use SQLite for simplicity)
      GF_DATABASE_TYPE: sqlite3
      GF_DATABASE_PATH: /var/lib/grafana/grafana.db
      # Disable analytics
      GF_ANALYTICS_REPORTING_ENABLED: 'false'
      GF_ANALYTICS_CHECK_FOR_UPDATES: 'false'
      # Allow embedding
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
    volumes:
      - /mnt/gluster/fastpool/grafana/data:/var/lib/grafana
    networks:
      - metrics_network
      - public_network
#    ports:
#      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    user: "0:0"  # Run as root to handle NFS permissions

networks:
  metrics_network:
    external: true
  public_network:
    external: true