version: '3.8'

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:14
    environment:
      # English language
      LANG: en
      # External hostname
      WG_HOST: vpn.vicugna.party
      # Optional parameters:
      PASSWORD_HASH: ${PASSWORD_HASH}
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      replicas: 1
      # No placement constraints - can run on any node
      restart_policy:
        condition: on-failure
    networks:
      - public_network

volumes:
  etc_wireguard:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.11,rw,soft,nolock
      device: ":/mnt/Main/wireguard"

networks:
  public_network:
    external: true
    # Assuming this network already exists in your swarm
